<?php
/*
 * Изменено: 22 ноября 2021, понедельник
 * Автор: Артамонов Денис <software.engineer@internet.ru>
 * copyright (c) 2021
 */

/**
 * @global CMain $APPLICATION
 */
$GLOBALS["HIDE_BREADCRUMB"] = true;
require $_SERVER['DOCUMENT_ROOT'] . '/bitrix/header.php';
$APPLICATION->SetTitle("Каталог товаров");
$APPLICATION->SetPageProperty("title", "Каталог товаров | Интернет-магазин Звенящие Кедры");
$APPLICATION->SetPageProperty("description", "");
$APPLICATION->SetPageProperty("keywords", "");

$SORT = "SORT";
$ORDER = "asc";
if($_GET["sort"]=="price")$SORT = "catalog_PRICE_12";
if($_GET["sort"]=="price_down") {
	$SORT = "catalog_PRICE_12";
	$ORDER = "desc";
}
if($_GET["sort"]=="date")$SORT = "created_date";
if($_GET["PAGEN_1"] == 1)localRedirect($APPLICATION->GetCurPageParam("", array("PAGEN_1")) );

//if (\Native\App\Template::isNewVersion()) {
?>
	<?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"megre_wizart", 
	array(
		"ROOT_FILTER" => $_GET["filter"],
		"ACTION_VARIABLE" => "action",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"BASKET_URL" => "/cart/",
		"BIG_DATA_RCM_TYPE" => "personal",
		"BRAND_PROPERTY" => "PROIZVODITEL",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMMON_ADD_TO_BASKET_ACTION" => "ADD",
		"COMMON_SHOW_CLOSE_POPUP" => "N",
		"COMPATIBLE_MODE" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONVERT_CURRENCY" => "N",
		"DATA_LAYER_NAME" => "dataLayer",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "Y",
		"DETAIL_ADD_TO_BASKET_ACTION" => array(
			0 => "ADD",
		),
		"DETAIL_ADD_TO_BASKET_ACTION_PRIMARY" => array(
			0 => "ADD",
		),
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_BRAND_USE" => "N",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "Y",
		"DETAIL_DETAIL_PICTURE_MODE" => array(
			0 => "POPUP",
			1 => "MAGNIFIER",
		),
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"DETAIL_FB_USE" => "N",
		"DETAIL_IMAGE_RESOLUTION" => "16by9",
		"DETAIL_MAIN_BLOCK_OFFERS_PROPERTY_CODE" => array(
		),
		"DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(
		),
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
		"DETAIL_PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "Y",
		"DETAIL_SHOW_POPULAR" => "Y",
		"DETAIL_SHOW_SLIDER" => "Y",
		"DETAIL_SHOW_VIEWED" => "Y",
		"DETAIL_SLIDER_INTERVAL" => "3000",
		"DETAIL_SLIDER_PROGRESS" => "Y",
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_VK_API_ID" => "API_ID",
		"DETAIL_VK_USE" => "N",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISCOUNT_PERCENT_POSITION" => "bottom-right",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "Y",
		"ELEMENT_SORT_FIELD" => $SORT,
		"ELEMENT_SORT_FIELD2" => "sort",
		"ELEMENT_SORT_ORDER" => $ORDER,
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_HIDE_ON_MOBILE" => "N",
		"FILTER_NAME" => "arFilter",
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "RAZMER_NOGI",
			1 => "NAPOLNITEL",
			2 => "VID",
			3 => "TIP",
			4 => "MATERIAL",
			5 => "BESTSELLERY",
			6 => "NOVINKI",
			7 => "RASPRODAZHA",
			8 => "REKOMENDUEM",
			9 => "",
		),
		"FILTER_PRICE_CODE" => array(
			0 => "BASE",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "PROIZVODITEL",
			1 => "NEWPRODUCT",
			2 => "SPECIALOFFER",
			3 => "RECOMMENDED",
			4 => "SALELEADER",
			5 => "OFFER_WEEK",
			6 => "VID_MASLA",
			7 => "NAZNACHENIE",
			8 => "NAPOLNITEL",
			9 => "TIP",
			10 => "TIP_VOLOS",
			11 => "TIP_KOZHI",
			12 => "",
		),
		"FILTER_VIEW_MODE" => "VERTICAL",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "L",
		"IBLOCK_ID" => "37",
		"IBLOCK_TYPE" => "1c_catalog",
		"INCLUDE_SUBSECTIONS" => "A",
		"INSTANT_RELOAD" => "Y",
		"LABEL_PROP" => array(
		),
		"LAZY_LOAD" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "38",
		"LINK_IBLOCK_TYPE" => "1c_catalog",
		"LINK_PROPERTY_SID" => "CML2_LINK",
		"LIST_BROWSER_TITLE" => "UF_TITLE",
		"LIST_ENLARGE_PRODUCT" => "STRICT",
		"LIST_META_DESCRIPTION" => "UF_DESCRIPTION",
		"LIST_META_KEYWORDS" => "UF_KEYWORDS",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_LIMIT" => "5",
		"LIST_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"LIST_PROPERTY_CODE_MOBILE" => array(
		),
		"LIST_SHOW_SLIDER" => "Y",
		"LIST_SLIDER_INTERVAL" => "3000",
		"LIST_SLIDER_PROGRESS" => "Y",
		"LOAD_ON_SCROLL" => "N",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_LAZY_LOAD" => "Показать больше",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_COMMENTS_TAB" => "Комментарии",
		"MESS_DESCRIPTION_TAB" => "Описание",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"MESS_PRICE_RANGES_TITLE" => "Цены",
		"MESS_PROPERTIES_TAB" => "Характеристики",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "asc",
		"OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "Y",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "modern",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "18",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
			0 => "Розница",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_DISPLAY_MODE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"SEARCH_CHECK_DATES" => "Y",
		"SEARCH_NO_WORD_LOGIC" => "Y",
		"SEARCH_PAGE_RESULT_COUNT" => "20",
		"SEARCH_RESTART" => "Y",
		"SEARCH_USE_LANGUAGE_GUESS" => "Y",
		"SEARCH_USE_SEARCH_RESULT_ORDER" => "Y",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTION_ADD_TO_BASKET_ACTION" => "ADD",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"SECTION_COUNT_ELEMENTS" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_CODE",
		"SECTION_TOP_DEPTH" => "3",
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SHOW_DEACTIVATED" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_SKU_DESCRIPTION" => "N",
		"SHOW_TOP_ELEMENTS" => "Y",
		"SIDEBAR_DETAIL_SHOW" => "N",
		"SIDEBAR_PATH" => "",
		"SIDEBAR_SECTION_SHOW" => "N",
		"TEMPLATE_THEME" => "",
		"TOP_ADD_TO_BASKET_ACTION" => "ADD",
		"TOP_ELEMENT_COUNT" => "8",
		"TOP_ELEMENT_SORT_FIELD" => "shows",
		"TOP_ELEMENT_SORT_FIELD2" => "sort",
		"TOP_ELEMENT_SORT_ORDER" => "desc",
		"TOP_ELEMENT_SORT_ORDER2" => "desc",
		"TOP_ENLARGE_PRODUCT" => "STRICT",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_LIMIT" => "5",
		"TOP_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"TOP_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false}]",
		"TOP_SHOW_SLIDER" => "Y",
		"TOP_SLIDER_INTERVAL" => "3000",
		"TOP_SLIDER_PROGRESS" => "Y",
		"TOP_VIEW_MODE" => "SECTION",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USE_BIG_DATA" => "N",
		"USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
		"USE_COMPARE" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_FILTER" => "Y",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"USE_GIFTS_SECTION" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"USE_REVIEW" => "Y",
		"USE_SALE_BESTSELLERS" => "Y",
		"USE_STORE" => "N",
		"COMPONENT_TEMPLATE" => "megre_wizart",
		"FILE_404" => "",
		"MESSAGES_PER_PAGE" => "10",
		"USE_CAPTCHA" => "Y",
		"REVIEW_AJAX_POST" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"FORUM_ID" => "1",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "Y",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?>
<?
/*} else {
	$APPLICATION->IncludeComponent(
		"alexkova.market:catalog",
		"shop",
		[
			"ACTION_VARIABLE"                       => "action",
			"ADDITIONAL_DETAIL_INFO"                => "/include/additional_detail_info.php",
			"ADDITIONAL_SKU_PIC_2_SLIDER"           => "N",
			"ADDITIONAL_TAB_SHOW"                   => "N",
			"ADD_ELEMENT_CHAIN"                     => "N",
			"ADD_PICT_PROP"                         => "MORE_PHOTO",
			"ADD_PROPERTIES_TO_BASKET"              => "Y",
			"ADD_SECTIONS_CHAIN"                    => "N",
			"AJAX_MODE"                             => "N",
			"AJAX_OPTION_ADDITIONAL"                => "",
			"AJAX_OPTION_HISTORY"                   => "N",
			"AJAX_OPTION_JUMP"                      => "N",
			"AJAX_OPTION_STYLE"                     => "Y",
			"ALSO_BUY_ELEMENT_COUNT"                => "8",
			"ALSO_BUY_MIN_BUYES"                    => "1",
			"ALSO_BUY_TITLE"                        => "С этим товаром покупают",
			"ANOUNCE_TRUNCATE_LEN"                  => "",
			"ARTICLE_POSITION"                      => "none",
			"BASKET_URL"                            => "/personal/basket.php",
			"BESTSALLERS_CNT"                       => "4",
			"BESTSALLERS_SORT"                      => "50",
			"BESTSALLERS_TITLE"                     => "Лидеры продаж",
			"BESTSALLERS_WERE_SHOW"                 => "left",
			"BIG_DATA_CNT"                          => "4",
			"BIG_DATA_RCM_TYPE"                     => "bestsell",
			"BIG_DATA_TITLE"                        => "Персональные рекомендации",
			"BXR_GIFT_NOTICE_TEXT"                  => "",
			"CACHE_FILTER"                          => "N",
			"CACHE_GROUPS"                          => "Y",
			"CACHE_TIME"                            => "86400",
			"CACHE_TYPE"                            => "N",
			"CATALOG_DEFAULT_SORT"                  => "",
			"CATALOG_DEFAULT_SORT_ORDER"            => "desc",
			"CATALOG_VIEW_SHOW"                     => "Y",
			"CHANGE_TITLE_SKU"                      => "N",
			"CHECK_DATES"                           => "N",
			"CHILD_MENU_TYPE"                       => "left",
			"COMMON_ADD_TO_BASKET_ACTION"           => "ADD",
			"COMPARE_ELEMENT_SORT_FIELD"            => "sort",
			"COMPARE_ELEMENT_SORT_ORDER"            => "desc",
			"COMPARE_FIELD_CODE"                    => [
				0 => "NAME",
				1 => "PREVIEW_TEXT",
				2 => "PREVIEW_PICTURE",
				3 => "",
			],
			"COMPARE_NAME"                          => "CATALOG_COMPARE_LIST",
			"COMPARE_OFFERS_FIELD_CODE"             => [
				0 => "NAME",
				1 => "PREVIEW_TEXT",
				2 => "PREVIEW_PICTURE",
				3 => "",
			],
			"COMPARE_OFFERS_PROPERTY_CODE"          => [
				0 => "VES_TOVARNOGO_PREDLOZHENIYA",
				1 => "VES",
				2 => "CML2_BASE_UNIT",
				3 => "RAZMER",
				4 => "NAPOLNITEL",
				5 => "VID",
				6 => "TIP",
				7 => "MATERIAL",
				8 => "SOSTAV_1",
				9 => "",
			],
			"COMPARE_POSITION"                      => "top left",
			"COMPARE_POSITION_FIXED"                => "Y",
			"COMPARE_PROPERTY_CODE"                 => [
				0 => "PROIZVODITEL",
				1 => "SOSTAV",
				2 => "MATERIAL",
				3 => "SOSTAV_1",
				4 => "NAZNACHENIE",
				5 => "HIT",
				6 => "NEW",
				7 => "ACTION",
				8 => "RECCOMEND",
				9 => "",
			],
			"COMPONENT_TEMPLATE"                    => "shop",
			"CONVERT_CURRENCY"                      => "N",
			"CURRENCY_ID"                           => "RUB",
			"DELAY"                                 => "N",
			"DETAIL_ADD_DETAIL_TO_SLIDER"           => "Y",
			"DETAIL_ADD_DETAIL_TO_SLIDER_SKU"       => "Y",
			"DETAIL_ADD_TO_BASKET_ACTION"           => [
				0 => "BUY",
			],
			"DETAIL_BLOG_EMAIL_NOTIFY"              => "Y",
			"DETAIL_BLOG_URL"                       => "catalog_comments_zg",
			"DETAIL_BLOG_USE"                       => "Y",
			"DETAIL_BRAND_USE"                      => "N",
			"DETAIL_BROWSER_TITLE"                  => "-",
			"DETAIL_CHECK_SECTION_ID_VARIABLE"      => "N",
			"DETAIL_DETAIL_PICTURE_MODE"            => "MAGNIFIER",
			"DETAIL_DISPLAY_NAME"                   => "Y",
			"DETAIL_DISPLAY_PREVIEW_TEXT_MODE"      => "S",
			"DETAIL_DISPLAY_SHOW_FILES"             => "Y",
			"DETAIL_DISPLAY_SHOW_VIDEO"             => "Y",
			"DETAIL_FB_USE"                         => "N",
			"DETAIL_META_DESCRIPTION"               => "-",
			"DETAIL_META_KEYWORDS"                  => "-",
			"DETAIL_OFFERS_FIELD_CODE"              => [
				0 => "NAME",
				1 => "PREVIEW_TEXT",
				2 => "PREVIEW_PICTURE",
				3 => "",
			],
			"DETAIL_OFFERS_PROPERTY_CODE"           => [
				0  => "OBEM_",
				1  => "SOSTAV",
				2  => "PEREPLET",
				3  => "RAZMER",
				4  => "SODERZHANIE_ZHIVITSY",
				5  => "SEMYA",
				6  => "RAZMER_NOGI",
				7  => "DEYSTVIE",
				8  => "NAPOLNITEL",
				9  => "VID",
				10 => "TIP",
				11 => "UPAKOVKA",
				12 => "MATERIAL",
				13 => "SOSTAV_1",
				14 => "NA_KAKOM_MASLE_OSNOVAN",
				15 => "NAZNACHENIE",
				16 => "BESTSELLERY",
				17 => "TIP_KOZHI",
				18 => "KONSISTENTSIYA",
				19 => "VID_MASLA",
				20 => "VES_TOVARNOGO_PREDLOZHENIYA",
				21 => "",
			],
			"DETAIL_PROPERTY_CODE"                  => [
				0  => "PROIZVODITEL",
				1  => "SOSTAV",
				2  => "TIP",
				3  => "DEYSTVIE",
				4  => "NAPOLNITEL",
				5  => "VID_PRODUKTA",
				6  => "TIP_VOLOS",
				7  => "UPAKOVKA",
				8  => "MATERIAL",
				9  => "SOSTAV_1",
				10 => "NA_KAKOM_MASLE_OSNOVAN",
				11 => "TIP_KOZHI",
				12 => "ZNACHOK_AKTSIYA",
				13 => "KONSISTENTSIYA",
				14 => "VID_MASLA",
				15 => "NAZNACHENIE",
				16 => "SPECIALOFFER",
				17 => "CML2_TRAITS_VES",
				18 => "MIN_PRICE",
				19 => "HIT",
				20 => "NEW",
				21 => "ACTION",
				22 => "RECCOMEND",
				23 => "",
			],
			"DETAIL_SET_CANONICAL_URL"              => "Y",
			"DETAIL_SHOW_BASIS_PRICE"               => "Y",
			"DETAIL_SHOW_MAX_QUANTITY"              => "N",
			"DETAIL_STRICT_SECTION_CHECK"           => "N",
			"DETAIL_USE_COMMENTS"                   => "Y",
			"DETAIL_USE_VOTE_RATING"                => "N",
			"DETAIL_VK_USE"                         => "N",
			"DETAIL_VOTE_DISPLAY_AS_RATING"         => "rating",
			"DISPLAY_BOTTOM_PAGER"                  => "Y",
			"DISPLAY_ELEMENT_SELECT_BOX"            => "N",
			"DISPLAY_TOP_PAGER"                     => "N",
			"ELEMENT_SORT_FIELD"                    => "sort",
			"ELEMENT_SORT_FIELD2"                   => "timestamp_x",
			"ELEMENT_SORT_ORDER"                    => "asc",
			"ELEMENT_SORT_ORDER2"                   => "desc",
			"FILTER_FIELD_CODE"                     => [
				0 => "",
				1 => "",
			],
			"FILTER_NAME"                           => "arFilter",
			"FILTER_OFFERS_FIELD_CODE"              => [
				0 => "",
				1 => "",
			],
			"FILTER_OFFERS_PROPERTY_CODE"           => [
				0  => "VES_TORGOVOGO_PREDLOZHENIYA",
				1  => "OBEM_",
				2  => "SOSTAV",
				3  => "CML2_ARTICLE",
				4  => "CML2_BASE_UNIT",
				5  => "PEREPLET",
				6  => "CML2_MANUFACTURER",
				7  => "CML2_TRAITS",
				8  => "CML2_TAXES",
				9  => "CML2_ATTRIBUTES",
				10 => "CML2_BAR_CODE",
				11 => "RAZMER",
				12 => "SODERZHANIE_ZHIVITSY",
				13 => "SEMYA",
				14 => "RAZMER_NOGI",
				15 => "DEYSTVIE",
				16 => "NAPOLNITEL",
				17 => "VID",
				18 => "TIP",
				19 => "UPAKOVKA",
				20 => "MATERIAL",
				21 => "SOSTAV_1",
				22 => "NA_KAKOM_MASLE_OSNOVAN",
				23 => "NAZNACHENIE",
				24 => "ZNACHOK_AKTSIYA",
				25 => "TIP_KOZHI",
				26 => "ZNACHOK_NOVINKA",
				27 => "KONSISTENTSIYA",
				28 => "VID_MASLA",
				29 => "ZNACHOK_EST",
				30 => "ZNACHOK_RASPRODAZHA",
				31 => "ZNACHOK_KHIT_PRODAZH",
				32 => "PRISUTSTVIE_V_INTERNET_MAGAZINE",
				33 => "VES",
				34 => "VES_TOVARNOGO_PREDLOZHENIYA",
				35 => "",
			],
			"FILTER_PRICE_CODE"                     => [
				0 => "Розница",
			],
			"FILTER_PROPERTY_CODE"                  => [
				0  => "PROIZVODITEL",
				1  => "SOSTAV",
				2  => "TIP",
				3  => "DEYSTVIE",
				4  => "NAPOLNITEL",
				5  => "VID_PRODUKTA",
				6  => "TIP_VOLOS",
				7  => "UPAKOVKA",
				8  => "MATERIAL",
				9  => "SOSTAV_1",
				10 => "NA_KAKOM_MASLE_OSNOVAN",
				11 => "TIP_KOZHI",
				12 => "KONSISTENTSIYA",
				13 => "VID_MASLA",
				14 => "NAZNACHENIE",
				15 => "HIT",
				16 => "NEW",
				17 => "ACTION",
				18 => "RECCOMEND",
				19 => "",
			],
			"FILTER_SKU_PHOTO"                      => "N",
			"FILTER_VIEW_MODE"                      => "VERTICAL",
			"GIFTS_DETAIL_BLOCK_TITLE"              => "Выберите один из подарков",
			"GIFTS_DETAIL_HIDE_BLOCK_TITLE"         => "N",
			"GIFTS_DETAIL_PAGE_ELEMENT_COUNT"       => "3",
			"GIFTS_DETAIL_TAB_TITLE"                => "Подарки",
			"GIFTS_HIDE_NOT_AVAILABLE"              => "N",
			"GIFTS_MESS_BTN_BUY"                    => "Выбрать",
			"GIFTS_PLACE"                           => "TOP",
			"GIFTS_SECTION_LIST_BLOCK_TITLE"        => "Подарки к товарам этого раздела",
			"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE"   => "N",
			"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "3",
			"GROUP_PRICE_COUNT"                     => "count",
			"HIDE_NOT_AVAILABLE"                    => "N",
			"HIDE_OFFERS_LIST"                      => "N",
			"HIDE_PREVIEW_PROPS_INLIST"             => "Y",
			"HOVER_TEMPLATE"                        => "classic",
			"IBLOCK_ID"                             => "37",
			"IBLOCK_TYPE"                           => "1c_catalog",
			"INCLUDE_SUBSECTIONS"                   => "Y",
			"IN_STOCK"                              => "В наличии",
			"LEFT_MENU_TEMPLATE"                    => "left_hover",
			"LINK_ELEMENTS_URL"                     => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
			"LINK_IBLOCK_ID"                        => "38",
			"LINK_IBLOCK_TYPE"                      => "1c_catalog",
			"LINK_PROPERTY_SID"                     => "CML2_LINK",
			"LIST_BROWSER_TITLE"                    => "UF_TITLE",
			"LIST_META_DESCRIPTION"                 => "UF_DESCRIPTION",
			"LIST_META_KEYWORDS"                    => "UF_KEYWORDS",
			"LIST_OFFERS_FIELD_CODE"                => [
				0 => "NAME",
				1 => "PREVIEW_TEXT",
				2 => "PREVIEW_PICTURE",
				3 => "",
			],
			"LIST_OFFERS_LIMIT"                     => "5",
			"LIST_OFFERS_PROPERTY_CODE"             => [
				0  => "OBEM_",
				1  => "SOSTAV",
				2  => "PEREPLET",
				3  => "RAZMER",
				4  => "SODERZHANIE_ZHIVITSY",
				5  => "SEMYA",
				6  => "RAZMER_NOGI",
				7  => "DEYSTVIE",
				8  => "NAPOLNITEL",
				9  => "VID",
				10 => "TIP",
				11 => "UPAKOVKA",
				12 => "MATERIAL",
				13 => "SOSTAV_1",
				14 => "NA_KAKOM_MASLE_OSNOVAN",
				15 => "NAZNACHENIE",
				16 => "TIP_KOZHI",
				17 => "KONSISTENTSIYA",
				18 => "VID_MASLA",
				19 => "VES",
				20 => "",
			],
			"LIST_PROPERTY_CODE"                    => [
				0  => "PROIZVODITEL",
				1  => "TIP",
				2  => "DEYSTVIE",
				3  => "NAPOLNITEL",
				4  => "VID_PRODUKTA",
				5  => "TIP_VOLOS",
				6  => "UPAKOVKA",
				7  => "MATERIAL",
				8  => "SOSTAV_1",
				9  => "NA_KAKOM_MASLE_OSNOVAN",
				10 => "TIP_KOZHI",
				11 => "KONSISTENTSIYA",
				12 => "VID_MASLA",
				13 => "NAZNACHENIE",
				14 => "HIT",
				15 => "NEW",
				16 => "ACTION",
				17 => "RECCOMEND",
				18 => "",
			],
			"MAX_LEVEL"                             => "3",
			"MESSAGE_404"                           => "",
			"MESS_BTN_BUY"                          => "",
			"MESS_BTN_REQUEST"                      => "Оставить заявку",
			"NOT_IN_STOCK"                          => "Нет в наличии",
			"NO_TABS"                               => "N",
			"NO_WORD_LOGIC"                         => "N",
			"OFFERS_CART_PROPERTIES"                => [
				0 => "VES_TORGOVOGO_PREDLOZHENIYA",
			],
			"OFFERS_SORT_FIELD"                     => "SORT",
			"OFFERS_SORT_FIELD2"                    => "SORT",
			"OFFERS_SORT_ORDER"                     => "asc",
			"OFFERS_SORT_ORDER2"                    => "asc",
			"OFFERS_VIEW"                           => "CHOISE",
			"OFFER_ADD_PICT_PROP"                   => "MORE_PHOTO",
			"OFFER_PRICE_SHOW_FROM"                 => "Y",
			"OFFER_TREE_PROPS"                      => [
				0 => "OBEM_",
				1 => "SOSTAV",
				2 => "PEREPLET",
				3 => "RAZMER",
				4 => "SODERZHANIE_ZHIVITSY",
				5 => "SEMYA",
				6 => "RAZMER_NOGI",
			],
			"PAGER_BASE_LINK_ENABLE"                => "N",
			"PAGER_DESC_NUMBERING"                  => "N",
			"PAGER_DESC_NUMBERING_CACHE_TIME"       => "3600000",
			"PAGER_SHOW_ALL"                        => "Y",
			"PAGER_SHOW_ALWAYS"                     => "N",
			"PAGER_TEMPLATE"                        => "round",
			"PAGER_TITLE"                           => "Товары",
			"PAGE_ELEMENT_COUNT"                    => "16",
			"PAGE_ELEMENT_COUNT_SHOW"               => "Y",
			"PARTIAL_PRODUCT_PROPERTIES"            => "Y",
			"PICTURE_SECTION"                       => "N",
			"PICTURE_SECTION_HOVER"                 => "N",
			"PREVIEW_DETAIL_PROPERTY_CODE"          => [
				0 => "",
				1 => "",
			],
			"PREVIEW_TRUNCATE_LEN"                  => "",
			"PRICE_CODE"                            => [
				0 => "Розница",
			],
			"PRICE_VAT_INCLUDE"                     => "Y",
			"PRICE_VAT_SHOW_VALUE"                  => "N",
			"PRODUCT_DISPLAY_MODE"                  => "Y",
			"PRODUCT_ID_VARIABLE"                   => "id",
			"PRODUCT_PROPERTIES"                    => [
				0 => "PROIZVODITEL",
			],
			"PRODUCT_PROPS_VARIABLE"                => "prop",
			"PRODUCT_QUANTITY_VARIABLE"             => "quantity",
			"PROPS_TAB_VIEW"                        => "TABLE",
			"QTY_LESS_GOODS_TEXT"                   => "мало",
			"QTY_MANY_GOODS_INT"                    => "5",
			"QTY_MANY_GOODS_TEXT"                   => "много",
			"QTY_SHOW_TYPE"                         => "NUM",
			"RCM_COUNT_DETAIL"                      => "4",
			"RCM_NAME_DETAIL"                       => "Персональные рекомендации",
			"RCM_TYPE_DETAIL"                       => "similar_sell",
			"RESTART"                               => "Y",
			"ROOT_MENU_TYPE"                        => "left",
			"SECTIONS_MAIN_VIEW_MODE"               => "LIST",
			"SECTIONS_SHOW_DESCRIPTION"             => "N",
			"SECTIONS_VIEW_MODE"                    => "LIST",
			"SECTION_ADD_TO_BASKET_ACTION"          => "ADD",
			"SECTION_BACKGROUND_IMAGE"              => "-",
			"SECTION_COUNT_ELEMENTS"                => "Y",
			"SECTION_ID_VARIABLE"                   => "SECTION_ID",
			"SECTION_TOP_DEPTH"                     => "2",
			"SEF_FOLDER"                            => "/catalog/",
			"SEF_MODE"                              => "Y",
			"SET_LAST_MODIFIED"                     => "N",
			"SET_STATUS_404"                        => "Y",
			"SET_TITLE"                             => "Y",
			"SHOWS_BIGDATA_DETAIL"                  => "N",
			"SHOW_404"                              => "N",
			"SHOW_CATALOG_QUANTITY"                 => "Y",
			"SHOW_CATALOG_QUANTITY_CNT"             => "N",
			"SHOW_DEACTIVATED"                      => "N",
			"SHOW_DISCOUNT_PERCENT"                 => "Y",
			"SHOW_GIFTS_DETAIL_NOTICE"              => "N",
			"SHOW_LEFT_MENU"                        => "Y",
			"SHOW_MAIN_INSTEAD_NF_SKU"              => "N",
			"SHOW_MEASURE"                          => "N",
			"SHOW_OFFER_PIC_BYCLICK"                => "Y",
			"SHOW_OLD_PRICE"                        => "Y",
			"SHOW_PRICE_COUNT"                      => "1",
			"SHOW_PRICE_NAME"                       => "N",
			"SHOW_SECTION_DESC"                     => "bottom",
			"SHOW_SECTION_SEO"                      => "N",
			"SIDEBAR_DETAIL_SHOW"                   => "Y",
			"SIDEBAR_PATH"                          => "",
			"SIDEBAR_SECTION_SHOW"                  => "Y",
			"SKU_PROPS_SHOW_TYPE"                   => "square",
			"SKU_SORT_PARAMS"                       => "N",
			"STYLE_MENU"                            => "colored_light",
			"STYLE_MENU_HOVER"                      => "colored_light",
			"SUBMENU"                               => "ACTIVE_SHOW",
			"THEME"                                 => "default",
			"TILE_SHOW_PROPERTIES"                  => "N",
			"TITLE_MENU"                            => "Каталог",
			"TOP_ADD_TO_BASKET_ACTION"              => "ADD",
			"USE_ALSO_BUY"                          => "Y",
			"USE_BIG_DATA"                          => "Y",
			"USE_COMMON_SETTINGS_BASKET_POPUP"      => "N",
			"USE_COMPARE"                           => "N",
			"USE_ELEMENT_COUNTER"                   => "Y",
			"USE_EXT"                               => "Y",
			"USE_FAVORITES"                         => "Y",
			"USE_FILTER"                            => "Y",
			"USE_GIFTS_DETAIL"                      => "N",
			"USE_GIFTS_SECTION"                     => "N",
			"USE_LANGUAGE_GUESS"                    => "N",
			"USE_MAIN_ELEMENT_SECTION"              => "N",
			"USE_ONE_CLICK"                         => "Y",
			"USE_PRICE_COUNT"                       => "N",
			"USE_PRODUCT_QUANTITY"                  => "Y",
			"USE_SALE_BESTSELLERS"                  => "N",
			"USE_SHARE"                             => "Y",
			"USE_STORE"                             => "N",
			"VIDEO_PLAYER"                          => "MEJ",
			"VIDEO_PLAYER_FULLSCREEN"               => "N",
			"VIDEO_TYPE"                            => "GRID",
			"VIEWED_PRODUCTS_BLOCK_TITLE"           => "Просмотренные товары",
			"VIEWED_PRODUCTS_CNT"                   => "4",
			"VIEWED_PRODUCTS_SHOW"                  => "Y",
			"VIEWED_PRODUCTS_SORT"                  => "100",
			"VIEWED_PRODUCTS_WERE_SHOW"             => "left",
			"ZOOM_ON"                               => "Y",
			"COMPOSITE_FRAME_MODE"                  => "A",
			"COMPOSITE_FRAME_TYPE"                  => "AUTO",
			"SEF_URL_TEMPLATES"                     => [
				"sections"     => "",
				"section"      => "#SECTION_CODE#/",
				"element"      => "#SECTION_CODE#/#ELEMENT_CODE#/",
				"compare"      => "compare.php?action=#ACTION_CODE#",
				"smart_filter" => "#SECTION_ID#/filter/#SMART_FILTER_PATH#/apply/",
			],
			"VARIABLE_ALIASES"                      => [
				"compare" => [
					"ACTION_CODE" => "action",
				],
			],
		],
		false
	);
}*/
require($_SERVER['DOCUMENT_ROOT'] . '/bitrix/footer.php');
