<?
/*
 * Изменено: 09 декабря 2021, четверг
 * Автор: Артамонов Денис <software.engineer@internet.ru>
 * copyright (c) 2021
 */

header('HTTP/1.1 301 Moved Permanently');
header('Location: /sales-point');
exit();
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Адреса фирменных отделов");
?><? $APPLICATION->IncludeComponent(
		"bitrix:news",
		"map",
		[
				"ADD_ELEMENT_CHAIN"               => "Y",
				"ADD_SECTIONS_CHAIN"              => "Y",
				"AJAX_MODE"                       => "N",
				"AJAX_OPTION_ADDITIONAL"          => "",
				"AJAX_OPTION_HISTORY"             => "N",
				"AJAX_OPTION_JUMP"                => "N",
				"AJAX_OPTION_STYLE"               => "Y",
				"BROWSER_TITLE"                   => "-",
				"CACHE_FILTER"                    => "N",
				"CACHE_GROUPS"                    => "Y",
				"CACHE_TIME"                      => "36000000",
				"CACHE_TYPE"                      => "A",
				"CHECK_DATES"                     => "Y",
				"DETAIL_ACTIVE_DATE_FORMAT"       => "d.m.Y",
				"DETAIL_DISPLAY_BOTTOM_PAGER"     => "Y",
				"DETAIL_DISPLAY_TOP_PAGER"        => "N",
				"DETAIL_FIELD_CODE"               => [
						0 => "",
						1 => "",
				],
				"DETAIL_PAGER_SHOW_ALL"           => "Y",
				"DETAIL_PAGER_TEMPLATE"           => "",
				"DETAIL_PAGER_TITLE"              => "Страница",
				"DETAIL_PROPERTY_CODE"            => [
						0 => "",
						1 => "",
				],
				"DETAIL_SET_CANONICAL_URL"        => "N",
				"DISPLAY_BOTTOM_PAGER"            => "Y",
				"DISPLAY_DATE"                    => "N",
				"DISPLAY_NAME"                    => "Y",
				"DISPLAY_PICTURE"                 => "Y",
				"DISPLAY_PREVIEW_TEXT"            => "Y",
				"DISPLAY_TOP_PAGER"               => "N",
				"HIDE_LINK_WHEN_NO_DETAIL"        => "N",
				"IBLOCK_ID"                       => "53",
				"IBLOCK_TYPE"                     => "content",
				"INCLUDE_IBLOCK_INTO_CHAIN"       => "Y",
				"LIST_ACTIVE_DATE_FORMAT"         => "d.m.Y",
				"LIST_FIELD_CODE"                 => [
						0 => "",
						1 => "",
				],
				"LIST_PROPERTY_CODE"              => [
						0  => "SHOP",
						1  => "CITY",
						2  => "ADDRESS",
						3  => "TC",
						4  => "TIME",
						5  => "PHONE",
						6  => "PERSON",
						7  => "WWW",
						8  => "EMAIL",
						9  => "COMMENT",
						10 => "YANDEX_MAP",
						11 => "GOOGLE_MAP",
						12 => "EN_ADDRESS",
						13 => "EN_NAME",
						14 => "",
				],
				"MESSAGE_404"                     => "",
				"META_DESCRIPTION"                => "-",
				"META_KEYWORDS"                   => "-",
				"NEWS_COUNT"                      => "200",
				"PAGER_BASE_LINK_ENABLE"          => "N",
				"PAGER_DESC_NUMBERING"            => "N",
				"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
				"PAGER_SHOW_ALL"                  => "N",
				"PAGER_SHOW_ALWAYS"               => "N",
				"PAGER_TEMPLATE"                  => "round",
				"PAGER_TITLE"                     => "Новости",
				"PREVIEW_TRUNCATE_LEN"            => "",
				"SEF_MODE"                        => "Y",
				"SET_LAST_MODIFIED"               => "N",
				"SET_STATUS_404"                  => "N",
				"SET_TITLE"                       => "N",
				"SHOW_404"                        => "N",
				"SORT_BY1"                        => "NAME",
				"SORT_BY2"                        => "SORT",
				"SORT_ORDER1"                     => "ASC",
				"SORT_ORDER2"                     => "ASC",
				"STRICT_SECTION_CHECK"            => "N",
				"USE_CATEGORIES"                  => "N",
				"USE_FILTER"                      => "N",
				"USE_PERMISSIONS"                 => "N",
				"USE_RATING"                      => "N",
				"USE_REVIEW"                      => "N",
				"USE_RSS"                         => "N",
				"USE_SEARCH"                      => "N",
				"USE_SHARE"                       => "Y",
				"COMPONENT_TEMPLATE"              => "map",
				"SEF_FOLDER"                      => "/dealers/",
				"SHARE_HIDE"                      => "N",
				"SHARE_TEMPLATE"                  => "",
				"SHARE_HANDLERS"                  => [
						0 => "facebook",
						1 => "mailru",
						2 => "vk",
				],
				"SHARE_SHORTEN_URL_LOGIN"         => "",
				"SHARE_SHORTEN_URL_KEY"           => "",
				"TEMPLATE_THEME"                  => "blue",
				"MEDIA_PROPERTY"                  => "",
				"SLIDER_PROPERTY"                 => "",
				"LIST_USE_SHARE"                  => "N",
				"SEF_URL_TEMPLATES"               => [
						"news"    => "",
						"section" => "#SECTION_CODE#/",
						"detail"  => "#SECTION_CODE#/#ELEMENT_CODE#/",
				],
		],
		false
); ?><br><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>
